# .github/workflows/deploy.yml
name: Deploy to EKS

on:
  push:
    branches:
      - main      # Main branch pe push → trigger!

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Code lo
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: AWS configure karo
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Step 3: kubectl configure karo
    - name: Configure kubectl
      run: |
        aws eks update-kubeconfig \
          --region ap-south-1 \
          --name demo-cluster

    # Step 4: Deploy karo!
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/demo-app

    # Step 5: Status check karo
    - name: Check Pods
      run: |
        kubectl get pods
        kubectl get services